import Head from "next/head";
import Works from "../components/Works";

export default function works() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Works />
		</div>
	);
}
